package com.example.walletapplication.domain.entity;

/**
 * Enumeration of different types of search suggestions that can be provided to users.
 * Used to categorize and prioritize suggestions in the SearchBar component.
 */
public enum SearchSuggestionType {
    /**
     * Suggestions based on recent search queries performed by the user.
     */
    RECENT_SEARCH("Son Aramalar"),
    
    /**
     * Suggestions based on transaction descriptions in the database.
     */
    TRANSACTION_DESCRIPTION("İşlem Açıklamaları"),
    
    /**
     * Suggestions based on category names available in the system.
     */
    CATEGORY_NAME("Kategori Adları"),
    
    /**
     * Suggestions based on common amount patterns or ranges.
     */
    AMOUNT_SUGGESTION("Tutar Önerileri"),
    
    /**
     * Suggestions based on date patterns or common date ranges.
     */
    DATE_SUGGESTION("Tarih Önerileri");
    
    private final String displayName;
    
    SearchSuggestionType(String displayName) {
        this.displayName = displayName;
    }
    
    /**
     * Gets the localized display name for this suggestion type.
     * @return display name in Turkish
     */
    public String getDisplayName() {
        return displayName;
    }
    
    /**
     * Gets the priority order for this suggestion type.
     * Lower numbers indicate higher priority.
     * @return priority order (0-based)
     */
    public int getPriority() {
        switch (this) {
            case RECENT_SEARCH:
                return 0;
            case TRANSACTION_DESCRIPTION:
                return 1;
            case CATEGORY_NAME:
                return 2;
            case AMOUNT_SUGGESTION:
                return 3;
            case DATE_SUGGESTION:
                return 4;
            default:
                return 999;
        }
    }
    
    /**
     * Checks if this suggestion type is user-generated content.
     * @return true if suggestions come from user data
     */
    public boolean isUserGenerated() {
        return this == RECENT_SEARCH || this == TRANSACTION_DESCRIPTION;
    }
    
    /**
     * Checks if this suggestion type is system-generated.
     * @return true if suggestions are generated by the system
     */
    public boolean isSystemGenerated() {
        return this == CATEGORY_NAME || this == AMOUNT_SUGGESTION || this == DATE_SUGGESTION;
    }
}